### ISSUE TITLE
Please use sounfont Nokia for best quality sound Java games

### ISSUE THREAD

**Issue by Clover1211** [woesss/JL-Mod#49] opened 2022-06-06 03:17 UTC
my hope is that it will be granted please for the sound of music using nokia soundfonts so that the sound of the game on the midi section becomes better because for each device the sound is different, some are good, some are bad, but the default sound could be a nokia soundfont in the melody section of the game, please respond yes

**Comment by woesss** [comment] 2022-06-06 06:03
Duplicate of #27

**Closed** 2022-06-06 06:03 UTC
Labels: enhancement
