### ISSUE TITLE
WWE Smackdown VS RAW 2008 Not rendered well

### ISSUE THREAD

**Issue by Clover1211** [woesss/JL-Mod#59] opened 2022-06-17 15:30 UTC
**Build version:**
0.82.3
**Game version:**
1.0.0
**Game resolution:**
240x320
**Device model:**
RM2020
**Android version:**
10
**Description of the issue:**
The texture of the legs is not displayed properly
![Screenshot_2022-06-17-22-22-21-88_bb21746c14afd53cebb34e02cf7ac2a5](https://user-images.githubusercontent.com/106918881/174329871-70e5b84d-fe8d-480b-8b08-74e6ab52579b.jpg)

**Comment by woesss** [comment] 2022-06-17 19:44
Duplicate of #58

**Closed by woesss** 2022-06-17 19:44 UTC
Labels: bug
